In [21]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.8.0'

In [22]:
df = pd.read_excel('/content/Folds5x2_pp.xlsx')
df

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [23]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
x

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [24]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.2, random_state=0)

##Initialize The ANN

In [26]:
ann = tf.keras.models.Sequential()

##Creating Layers Of ANN

Input & 1st Hidden Layer

In [27]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

2nd Hidden Layer

In [28]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Output Layer

In [29]:
ann.add(tf.keras.layers.Dense(units=1))

we don't need any activation function on the output neuron in case of ANN Regression model

##Training The ANN

Compiling all the layers of ANN

In [30]:
ann.compile(optimizer='adam', loss='mean_squared_error')

In case of Continuous output or ANN Regression model, we use loss method = 'mean_squared_error'

Training The ANN

In [32]:
ann.fit(x_train, y_train, batch_size=32, epochs=200)

Epoch 1/200
60/60 [==============================] - 0s 1ms/step - loss: 77.1400
Epoch 2/200
60/60 [==============================] - 0s 1ms/step - loss: 76.2818
Epoch 3/200
60/60 [==============================] - 0s 1ms/step - loss: 73.7966
Epoch 4/200
60/60 [==============================] - 0s 1ms/step - loss: 72.2838
Epoch 5/200
60/60 [==============================] - 0s 1ms/step - loss: 70.5667
Epoch 6/200
60/60 [==============================] - 0s 1ms/step - loss: 69.0354
Epoch 7/200
60/60 [==============================] - 0s 1ms/step - loss: 68.0689
Epoch 8/200
60/60 [==============================] - 0s 1ms/step - loss: 66.8559
Epoch 9/200
60/60 [==============================] - 0s 2ms/step - loss: 65.7364
Epoch 10/200
60/60 [==============================] - 0s 1ms/step - loss: 63.6072
Epoch 11/200
60/60 [==============================] - 0s 1ms/step - loss: 62.5824
Epoch 12/200
60/60 [==============================] - 0s 1ms/step - loss: 61.2784
Epoch 13/200
60/60 [=====

##Predicting

In [34]:
y_pred = ann.predict(x_test)
y_pred

array([[430.93155],
       [462.33957],
       [466.09772],
       ...,
       [441.05222],
       [453.8478 ],
       [433.3538 ]], dtype=float32)

In [37]:
np.set_printoptions(precision=2)

In [40]:
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)), 1))

[[430.93 431.23]
 [462.34 460.01]
 [466.1  461.14]
 ...
 [441.05 440.96]
 [453.85 453.99]
 [433.35 430.57]]
